# Generated by Django 4.2.1 on 2023-05-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('Karnataka', 'Karnataka')], max_length=20)),
                ('class_ref', models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], max_length=20)),
                ('subject', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Maths', 'Maths'), ('Science', 'Science'), ('EVS', 'EVS')], max_length=50)),
                ('question_type', models.CharField(choices=[('MCQ', 'MCQ'), ('True or False', 'True or False'), ('Fill in the blanks', 'Fill in the blanks'), ('Match the following', 'Match the following'), ('Very Short Answers', 'Very Short Answers'), ('Short Answers', 'Short Answers'), ('Long Answers', 'Long Answers'), ('Very Long Answers', 'Very Long Answers')], max_length=50)),
                ('difficulty_level', models.CharField(choices=[('Easy', 'Easy'), ('Average', 'Average'), ('Difficult', 'Difficult')], max_length=20)),
                ('objective', models.CharField(choices=[('Remembering', 'Remembering'), ('Comprehension', 'Comprehension'), ('Expression', 'Expression'), ('Appreciation', 'Appreciation'), ('Understanding', 'Understanding'), ('Application', 'Application'), ('Skill', 'Skill')], max_length=50)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to='answers/')),
                ('question_text', models.TextField(blank=True, null=True)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('explanation_text', models.TextField(blank=True, null=True)),
                ('marks', models.PositiveSmallIntegerField()),
                ('approximate_time', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
